service:
  - type: web
    name: primer_deploy
    env: docker
    autoDeploy: false
    plan: free
    region: oregon
    envVars:
      - Key: ENV
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: False
      - key: CORS_ALLOW_ALL_ORIGINS
        sync: False
      - key: CORS_ALLOWED_ORIGINS
        sync: False
      - key: CSRF_TRUSTED_ORIGINS
        sync: False
      - key: CSRF_COOKIE_SECURE
        sync: False
      - key: DEBUG
        sync: False
      - key: POSTGRES_DB
        sync: False
      - key: POSTGRES_USER
        sync: False
      - key: POSTGRES_PASSWORD
        sync: False
      - key: POSTGRES_HOST
        sync: False
      - key: POSTGRES_PORT
        sync: false
